name: Testing

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.set-output.outputs.foo }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set outputs
        id: set-output
        run: |
          foo=$(echo 'bar')
          echo "foo=$foo" >> $GITHUB_OUTPUT

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Validate
        run: |
          echo "Needs Export: ${{ needs.job_1.outputs.foo }}
